name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to main
  workflow_dispatch: # Allows manual triggers

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Install Docusaurus CLI
        run: npm install @docusaurus/core@latest --save-dev

      - name: Build the site
        run: |
          export PATH=./node_modules/.bin:$PATH
          npx docusaurus build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build